[project]
name = "wrapper_utils"
version = "0.1.0"
description = "A couple of handy decorator functions"
authors = [
    { name="Danny" }
]

dependencies = [
    "numpy"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"